<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-OPLD0U4" name="loginCase" tests="6" failures="3" timestamp="6 Jan 2020 06:16:23 GMT" time="30.961" errors="0">
  <testcase name="login" time="1.087" classname="testCase.loginCase"/>
  <testcase name="login" time="0.467" classname="testCase.loginCase"/>
  <testcase name="login" time="0.418" classname="testCase.loginCase"/>
  <testcase name="login" time="8.321" classname="testCase.loginCase">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at util.Assertion.assertUrlContains(Assertion.java:27)
	at testCase.loginCase.login(loginCase.java:30)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="login" time="8.334" classname="testCase.loginCase">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at util.Assertion.assertUrlContains(Assertion.java:27)
	at testCase.loginCase.login(loginCase.java:30)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="loginTrue" time="8.284" classname="testCase.loginCase">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at util.Assertion.assertUrlContains(Assertion.java:27)
	at testCase.loginCase.loginTrue(loginCase.java:48)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- loginTrue -->
</testsuite> <!-- loginCase -->
